import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import BreadcrumbNavigation from "@/components/breadcrumb-navigation";
import Nav from "@/components/nav";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";

const quicksand = Quicksand({
	subsets: ["latin"],
	weight: ["400", "500", "700"],
	variable: "--font-sans",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					"min-h-screen bg-background font-sans antialiased dark:bg-zinc-900 dark:text-zinc-300",
					quicksand.variable,
				)}
			>
				<header className="shadow flex flex-row items-center justify-between h-16 px-4 md:px-8 sticky top-0 w-full z-50 bg-white">
					<div className="flex flex-row gap-x-4 items-center">
						<h1 className="text-2xl text-purple-500">
							<a href="/">Buzón de Quejas - BUAP</a>
						</h1>
						<div className="flex-row gap-x-4 items-center hidden md:flex">
							<BreadcrumbNavigation />
						</div>
					</div>
					<Nav />
				</header>
				<div className="relative min-h-[calc(100dvh-4rem)] overflow-y-auto mx-8">
					<div className="flex-row gap-x-4 items-center flex md:hidden mt-4">
						<BreadcrumbNavigation />
					</div>
					{children}
				</div>
				<Toaster />
			</body>
		</html>
	);
}
